// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoicerequest"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceRequestUpdate is the builder for updating InvoiceRequest entities.
type InvoiceRequestUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceRequestMutation
}

// Where appends a list predicates to the InvoiceRequestUpdate builder.
func (_u *InvoiceRequestUpdate) Where(ps ...predicate.InvoiceRequest) *InvoiceRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceRequestUpdate) SetUpdatedAt(v time.Time) *InvoiceRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceRequestUpdate) SetUserID(v int64) *InvoiceRequestUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableUserID(v *int64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPaymentOrderIds sets the "payment_order_ids" field.
func (_u *InvoiceRequestUpdate) SetPaymentOrderIds(v []int64) *InvoiceRequestUpdate {
	_u.mutation.SetPaymentOrderIds(v)
	return _u
}

// AppendPaymentOrderIds appends value to the "payment_order_ids" field.
func (_u *InvoiceRequestUpdate) AppendPaymentOrderIds(v []int64) *InvoiceRequestUpdate {
	_u.mutation.AppendPaymentOrderIds(v)
	return _u
}

// SetRedeemCodeIds sets the "redeem_code_ids" field.
func (_u *InvoiceRequestUpdate) SetRedeemCodeIds(v []int64) *InvoiceRequestUpdate {
	_u.mutation.SetRedeemCodeIds(v)
	return _u
}

// AppendRedeemCodeIds appends value to the "redeem_code_ids" field.
func (_u *InvoiceRequestUpdate) AppendRedeemCodeIds(v []int64) *InvoiceRequestUpdate {
	_u.mutation.AppendRedeemCodeIds(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *InvoiceRequestUpdate) SetAmount(v float64) *InvoiceRequestUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableAmount(v *float64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *InvoiceRequestUpdate) AddAmount(v float64) *InvoiceRequestUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetInvoiceType sets the "invoice_type" field.
func (_u *InvoiceRequestUpdate) SetInvoiceType(v string) *InvoiceRequestUpdate {
	_u.mutation.SetInvoiceType(v)
	return _u
}

// SetNillableInvoiceType sets the "invoice_type" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableInvoiceType(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetInvoiceType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *InvoiceRequestUpdate) SetTitle(v string) *InvoiceRequestUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableTitle(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTaxNo sets the "tax_no" field.
func (_u *InvoiceRequestUpdate) SetTaxNo(v string) *InvoiceRequestUpdate {
	_u.mutation.SetTaxNo(v)
	return _u
}

// SetNillableTaxNo sets the "tax_no" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableTaxNo(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetTaxNo(*v)
	}
	return _u
}

// ClearTaxNo clears the value of the "tax_no" field.
func (_u *InvoiceRequestUpdate) ClearTaxNo() *InvoiceRequestUpdate {
	_u.mutation.ClearTaxNo()
	return _u
}

// SetRecipientEmail sets the "recipient_email" field.
func (_u *InvoiceRequestUpdate) SetRecipientEmail(v string) *InvoiceRequestUpdate {
	_u.mutation.SetRecipientEmail(v)
	return _u
}

// SetNillableRecipientEmail sets the "recipient_email" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableRecipientEmail(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetRecipientEmail(*v)
	}
	return _u
}

// ClearRecipientEmail clears the value of the "recipient_email" field.
func (_u *InvoiceRequestUpdate) ClearRecipientEmail() *InvoiceRequestUpdate {
	_u.mutation.ClearRecipientEmail()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *InvoiceRequestUpdate) SetRemark(v string) *InvoiceRequestUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableRemark(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *InvoiceRequestUpdate) ClearRemark() *InvoiceRequestUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceRequestUpdate) SetStatus(v string) *InvoiceRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableStatus(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRejectReason sets the "reject_reason" field.
func (_u *InvoiceRequestUpdate) SetRejectReason(v string) *InvoiceRequestUpdate {
	_u.mutation.SetRejectReason(v)
	return _u
}

// SetNillableRejectReason sets the "reject_reason" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableRejectReason(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetRejectReason(*v)
	}
	return _u
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (_u *InvoiceRequestUpdate) ClearRejectReason() *InvoiceRequestUpdate {
	_u.mutation.ClearRejectReason()
	return _u
}

// SetInvoiceNo sets the "invoice_no" field.
func (_u *InvoiceRequestUpdate) SetInvoiceNo(v string) *InvoiceRequestUpdate {
	_u.mutation.SetInvoiceNo(v)
	return _u
}

// SetNillableInvoiceNo sets the "invoice_no" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableInvoiceNo(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetInvoiceNo(*v)
	}
	return _u
}

// ClearInvoiceNo clears the value of the "invoice_no" field.
func (_u *InvoiceRequestUpdate) ClearInvoiceNo() *InvoiceRequestUpdate {
	_u.mutation.ClearInvoiceNo()
	return _u
}

// SetInvoiceFilePath sets the "invoice_file_path" field.
func (_u *InvoiceRequestUpdate) SetInvoiceFilePath(v string) *InvoiceRequestUpdate {
	_u.mutation.SetInvoiceFilePath(v)
	return _u
}

// SetNillableInvoiceFilePath sets the "invoice_file_path" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableInvoiceFilePath(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetInvoiceFilePath(*v)
	}
	return _u
}

// ClearInvoiceFilePath clears the value of the "invoice_file_path" field.
func (_u *InvoiceRequestUpdate) ClearInvoiceFilePath() *InvoiceRequestUpdate {
	_u.mutation.ClearInvoiceFilePath()
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *InvoiceRequestUpdate) SetIssuedAt(v time.Time) *InvoiceRequestUpdate {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableIssuedAt(v *time.Time) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *InvoiceRequestUpdate) ClearIssuedAt() *InvoiceRequestUpdate {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetProcessedBy sets the "processed_by" field.
func (_u *InvoiceRequestUpdate) SetProcessedBy(v int64) *InvoiceRequestUpdate {
	_u.mutation.ResetProcessedBy()
	_u.mutation.SetProcessedBy(v)
	return _u
}

// SetNillableProcessedBy sets the "processed_by" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableProcessedBy(v *int64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetProcessedBy(*v)
	}
	return _u
}

// AddProcessedBy adds value to the "processed_by" field.
func (_u *InvoiceRequestUpdate) AddProcessedBy(v int64) *InvoiceRequestUpdate {
	_u.mutation.AddProcessedBy(v)
	return _u
}

// ClearProcessedBy clears the value of the "processed_by" field.
func (_u *InvoiceRequestUpdate) ClearProcessedBy() *InvoiceRequestUpdate {
	_u.mutation.ClearProcessedBy()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceRequestUpdate) SetUser(v *User) *InvoiceRequestUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the InvoiceRequestMutation object of the builder.
func (_u *InvoiceRequestUpdate) Mutation() *InvoiceRequestMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceRequestUpdate) ClearUser() *InvoiceRequestUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceRequestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceRequestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoicerequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceRequestUpdate) check() error {
	if v, ok := _u.mutation.InvoiceType(); ok {
		if err := invoicerequest.InvoiceTypeValidator(v); err != nil {
			return &ValidationError{Name: "invoice_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.invoice_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := invoicerequest.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxNo(); ok {
		if err := invoicerequest.TaxNoValidator(v); err != nil {
			return &ValidationError{Name: "tax_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.tax_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecipientEmail(); ok {
		if err := invoicerequest.RecipientEmailValidator(v); err != nil {
			return &ValidationError{Name: "recipient_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.recipient_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invoicerequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceNo(); ok {
		if err := invoicerequest.InvoiceNoValidator(v); err != nil {
			return &ValidationError{Name: "invoice_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.invoice_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceFilePath(); ok {
		if err := invoicerequest.InvoiceFilePathValidator(v); err != nil {
			return &ValidationError{Name: "invoice_file_path", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.invoice_file_path": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceRequest.user"`)
	}
	return nil
}

func (_u *InvoiceRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoicerequest.Table, invoicerequest.Columns, sqlgraph.NewFieldSpec(invoicerequest.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoicerequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PaymentOrderIds(); ok {
		_spec.SetField(invoicerequest.FieldPaymentOrderIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPaymentOrderIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, invoicerequest.FieldPaymentOrderIds, value)
		})
	}
	if value, ok := _u.mutation.RedeemCodeIds(); ok {
		_spec.SetField(invoicerequest.FieldRedeemCodeIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRedeemCodeIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, invoicerequest.FieldRedeemCodeIds, value)
		})
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(invoicerequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(invoicerequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.InvoiceType(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(invoicerequest.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxNo(); ok {
		_spec.SetField(invoicerequest.FieldTaxNo, field.TypeString, value)
	}
	if _u.mutation.TaxNoCleared() {
		_spec.ClearField(invoicerequest.FieldTaxNo, field.TypeString)
	}
	if value, ok := _u.mutation.RecipientEmail(); ok {
		_spec.SetField(invoicerequest.FieldRecipientEmail, field.TypeString, value)
	}
	if _u.mutation.RecipientEmailCleared() {
		_spec.ClearField(invoicerequest.FieldRecipientEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(invoicerequest.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(invoicerequest.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoicerequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RejectReason(); ok {
		_spec.SetField(invoicerequest.FieldRejectReason, field.TypeString, value)
	}
	if _u.mutation.RejectReasonCleared() {
		_spec.ClearField(invoicerequest.FieldRejectReason, field.TypeString)
	}
	if value, ok := _u.mutation.InvoiceNo(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceNo, field.TypeString, value)
	}
	if _u.mutation.InvoiceNoCleared() {
		_spec.ClearField(invoicerequest.FieldInvoiceNo, field.TypeString)
	}
	if value, ok := _u.mutation.InvoiceFilePath(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceFilePath, field.TypeString, value)
	}
	if _u.mutation.InvoiceFilePathCleared() {
		_spec.ClearField(invoicerequest.FieldInvoiceFilePath, field.TypeString)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(invoicerequest.FieldIssuedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(invoicerequest.FieldIssuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ProcessedBy(); ok {
		_spec.SetField(invoicerequest.FieldProcessedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProcessedBy(); ok {
		_spec.AddField(invoicerequest.FieldProcessedBy, field.TypeInt64, value)
	}
	if _u.mutation.ProcessedByCleared() {
		_spec.ClearField(invoicerequest.FieldProcessedBy, field.TypeInt64)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoicerequest.UserTable,
			Columns: []string{invoicerequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoicerequest.UserTable,
			Columns: []string{invoicerequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoicerequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceRequestUpdateOne is the builder for updating a single InvoiceRequest entity.
type InvoiceRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceRequestMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceRequestUpdateOne) SetUpdatedAt(v time.Time) *InvoiceRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceRequestUpdateOne) SetUserID(v int64) *InvoiceRequestUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableUserID(v *int64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPaymentOrderIds sets the "payment_order_ids" field.
func (_u *InvoiceRequestUpdateOne) SetPaymentOrderIds(v []int64) *InvoiceRequestUpdateOne {
	_u.mutation.SetPaymentOrderIds(v)
	return _u
}

// AppendPaymentOrderIds appends value to the "payment_order_ids" field.
func (_u *InvoiceRequestUpdateOne) AppendPaymentOrderIds(v []int64) *InvoiceRequestUpdateOne {
	_u.mutation.AppendPaymentOrderIds(v)
	return _u
}

// SetRedeemCodeIds sets the "redeem_code_ids" field.
func (_u *InvoiceRequestUpdateOne) SetRedeemCodeIds(v []int64) *InvoiceRequestUpdateOne {
	_u.mutation.SetRedeemCodeIds(v)
	return _u
}

// AppendRedeemCodeIds appends value to the "redeem_code_ids" field.
func (_u *InvoiceRequestUpdateOne) AppendRedeemCodeIds(v []int64) *InvoiceRequestUpdateOne {
	_u.mutation.AppendRedeemCodeIds(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *InvoiceRequestUpdateOne) SetAmount(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableAmount(v *float64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *InvoiceRequestUpdateOne) AddAmount(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetInvoiceType sets the "invoice_type" field.
func (_u *InvoiceRequestUpdateOne) SetInvoiceType(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetInvoiceType(v)
	return _u
}

// SetNillableInvoiceType sets the "invoice_type" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableInvoiceType(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetInvoiceType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *InvoiceRequestUpdateOne) SetTitle(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableTitle(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTaxNo sets the "tax_no" field.
func (_u *InvoiceRequestUpdateOne) SetTaxNo(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetTaxNo(v)
	return _u
}

// SetNillableTaxNo sets the "tax_no" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableTaxNo(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetTaxNo(*v)
	}
	return _u
}

// ClearTaxNo clears the value of the "tax_no" field.
func (_u *InvoiceRequestUpdateOne) ClearTaxNo() *InvoiceRequestUpdateOne {
	_u.mutation.ClearTaxNo()
	return _u
}

// SetRecipientEmail sets the "recipient_email" field.
func (_u *InvoiceRequestUpdateOne) SetRecipientEmail(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetRecipientEmail(v)
	return _u
}

// SetNillableRecipientEmail sets the "recipient_email" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableRecipientEmail(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetRecipientEmail(*v)
	}
	return _u
}

// ClearRecipientEmail clears the value of the "recipient_email" field.
func (_u *InvoiceRequestUpdateOne) ClearRecipientEmail() *InvoiceRequestUpdateOne {
	_u.mutation.ClearRecipientEmail()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *InvoiceRequestUpdateOne) SetRemark(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableRemark(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *InvoiceRequestUpdateOne) ClearRemark() *InvoiceRequestUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceRequestUpdateOne) SetStatus(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableStatus(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRejectReason sets the "reject_reason" field.
func (_u *InvoiceRequestUpdateOne) SetRejectReason(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetRejectReason(v)
	return _u
}

// SetNillableRejectReason sets the "reject_reason" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableRejectReason(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetRejectReason(*v)
	}
	return _u
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (_u *InvoiceRequestUpdateOne) ClearRejectReason() *InvoiceRequestUpdateOne {
	_u.mutation.ClearRejectReason()
	return _u
}

// SetInvoiceNo sets the "invoice_no" field.
func (_u *InvoiceRequestUpdateOne) SetInvoiceNo(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetInvoiceNo(v)
	return _u
}

// SetNillableInvoiceNo sets the "invoice_no" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableInvoiceNo(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetInvoiceNo(*v)
	}
	return _u
}

// ClearInvoiceNo clears the value of the "invoice_no" field.
func (_u *InvoiceRequestUpdateOne) ClearInvoiceNo() *InvoiceRequestUpdateOne {
	_u.mutation.ClearInvoiceNo()
	return _u
}

// SetInvoiceFilePath sets the "invoice_file_path" field.
func (_u *InvoiceRequestUpdateOne) SetInvoiceFilePath(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetInvoiceFilePath(v)
	return _u
}

// SetNillableInvoiceFilePath sets the "invoice_file_path" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableInvoiceFilePath(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetInvoiceFilePath(*v)
	}
	return _u
}

// ClearInvoiceFilePath clears the value of the "invoice_file_path" field.
func (_u *InvoiceRequestUpdateOne) ClearInvoiceFilePath() *InvoiceRequestUpdateOne {
	_u.mutation.ClearInvoiceFilePath()
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *InvoiceRequestUpdateOne) SetIssuedAt(v time.Time) *InvoiceRequestUpdateOne {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableIssuedAt(v *time.Time) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *InvoiceRequestUpdateOne) ClearIssuedAt() *InvoiceRequestUpdateOne {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetProcessedBy sets the "processed_by" field.
func (_u *InvoiceRequestUpdateOne) SetProcessedBy(v int64) *InvoiceRequestUpdateOne {
	_u.mutation.ResetProcessedBy()
	_u.mutation.SetProcessedBy(v)
	return _u
}

// SetNillableProcessedBy sets the "processed_by" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableProcessedBy(v *int64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetProcessedBy(*v)
	}
	return _u
}

// AddProcessedBy adds value to the "processed_by" field.
func (_u *InvoiceRequestUpdateOne) AddProcessedBy(v int64) *InvoiceRequestUpdateOne {
	_u.mutation.AddProcessedBy(v)
	return _u
}

// ClearProcessedBy clears the value of the "processed_by" field.
func (_u *InvoiceRequestUpdateOne) ClearProcessedBy() *InvoiceRequestUpdateOne {
	_u.mutation.ClearProcessedBy()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceRequestUpdateOne) SetUser(v *User) *InvoiceRequestUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the InvoiceRequestMutation object of the builder.
func (_u *InvoiceRequestUpdateOne) Mutation() *InvoiceRequestMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceRequestUpdateOne) ClearUser() *InvoiceRequestUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the InvoiceRequestUpdate builder.
func (_u *InvoiceRequestUpdateOne) Where(ps ...predicate.InvoiceRequest) *InvoiceRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceRequestUpdateOne) Select(field string, fields ...string) *InvoiceRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InvoiceRequest entity.
func (_u *InvoiceRequestUpdateOne) Save(ctx context.Context) (*InvoiceRequest, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceRequestUpdateOne) SaveX(ctx context.Context) *InvoiceRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceRequestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoicerequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceRequestUpdateOne) check() error {
	if v, ok := _u.mutation.InvoiceType(); ok {
		if err := invoicerequest.InvoiceTypeValidator(v); err != nil {
			return &ValidationError{Name: "invoice_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.invoice_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := invoicerequest.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxNo(); ok {
		if err := invoicerequest.TaxNoValidator(v); err != nil {
			return &ValidationError{Name: "tax_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.tax_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecipientEmail(); ok {
		if err := invoicerequest.RecipientEmailValidator(v); err != nil {
			return &ValidationError{Name: "recipient_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.recipient_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invoicerequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceNo(); ok {
		if err := invoicerequest.InvoiceNoValidator(v); err != nil {
			return &ValidationError{Name: "invoice_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.invoice_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceFilePath(); ok {
		if err := invoicerequest.InvoiceFilePathValidator(v); err != nil {
			return &ValidationError{Name: "invoice_file_path", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.invoice_file_path": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceRequest.user"`)
	}
	return nil
}

func (_u *InvoiceRequestUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoicerequest.Table, invoicerequest.Columns, sqlgraph.NewFieldSpec(invoicerequest.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoicerequest.FieldID)
		for _, f := range fields {
			if !invoicerequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoicerequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoicerequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PaymentOrderIds(); ok {
		_spec.SetField(invoicerequest.FieldPaymentOrderIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPaymentOrderIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, invoicerequest.FieldPaymentOrderIds, value)
		})
	}
	if value, ok := _u.mutation.RedeemCodeIds(); ok {
		_spec.SetField(invoicerequest.FieldRedeemCodeIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRedeemCodeIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, invoicerequest.FieldRedeemCodeIds, value)
		})
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(invoicerequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(invoicerequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.InvoiceType(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(invoicerequest.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxNo(); ok {
		_spec.SetField(invoicerequest.FieldTaxNo, field.TypeString, value)
	}
	if _u.mutation.TaxNoCleared() {
		_spec.ClearField(invoicerequest.FieldTaxNo, field.TypeString)
	}
	if value, ok := _u.mutation.RecipientEmail(); ok {
		_spec.SetField(invoicerequest.FieldRecipientEmail, field.TypeString, value)
	}
	if _u.mutation.RecipientEmailCleared() {
		_spec.ClearField(invoicerequest.FieldRecipientEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(invoicerequest.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(invoicerequest.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoicerequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RejectReason(); ok {
		_spec.SetField(invoicerequest.FieldRejectReason, field.TypeString, value)
	}
	if _u.mutation.RejectReasonCleared() {
		_spec.ClearField(invoicerequest.FieldRejectReason, field.TypeString)
	}
	if value, ok := _u.mutation.InvoiceNo(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceNo, field.TypeString, value)
	}
	if _u.mutation.InvoiceNoCleared() {
		_spec.ClearField(invoicerequest.FieldInvoiceNo, field.TypeString)
	}
	if value, ok := _u.mutation.InvoiceFilePath(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceFilePath, field.TypeString, value)
	}
	if _u.mutation.InvoiceFilePathCleared() {
		_spec.ClearField(invoicerequest.FieldInvoiceFilePath, field.TypeString)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(invoicerequest.FieldIssuedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(invoicerequest.FieldIssuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ProcessedBy(); ok {
		_spec.SetField(invoicerequest.FieldProcessedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProcessedBy(); ok {
		_spec.AddField(invoicerequest.FieldProcessedBy, field.TypeInt64, value)
	}
	if _u.mutation.ProcessedByCleared() {
		_spec.ClearField(invoicerequest.FieldProcessedBy, field.TypeInt64)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoicerequest.UserTable,
			Columns: []string{invoicerequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoicerequest.UserTable,
			Columns: []string{invoicerequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InvoiceRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoicerequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
