// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoicerequest"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceRequestCreate is the builder for creating a InvoiceRequest entity.
type InvoiceRequestCreate struct {
	config
	mutation *InvoiceRequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceRequestCreate) SetCreatedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableCreatedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvoiceRequestCreate) SetUpdatedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableUpdatedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *InvoiceRequestCreate) SetUserID(v int64) *InvoiceRequestCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPaymentOrderIds sets the "payment_order_ids" field.
func (_c *InvoiceRequestCreate) SetPaymentOrderIds(v []int64) *InvoiceRequestCreate {
	_c.mutation.SetPaymentOrderIds(v)
	return _c
}

// SetRedeemCodeIds sets the "redeem_code_ids" field.
func (_c *InvoiceRequestCreate) SetRedeemCodeIds(v []int64) *InvoiceRequestCreate {
	_c.mutation.SetRedeemCodeIds(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *InvoiceRequestCreate) SetAmount(v float64) *InvoiceRequestCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetInvoiceType sets the "invoice_type" field.
func (_c *InvoiceRequestCreate) SetInvoiceType(v string) *InvoiceRequestCreate {
	_c.mutation.SetInvoiceType(v)
	return _c
}

// SetNillableInvoiceType sets the "invoice_type" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableInvoiceType(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetInvoiceType(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *InvoiceRequestCreate) SetTitle(v string) *InvoiceRequestCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetTaxNo sets the "tax_no" field.
func (_c *InvoiceRequestCreate) SetTaxNo(v string) *InvoiceRequestCreate {
	_c.mutation.SetTaxNo(v)
	return _c
}

// SetNillableTaxNo sets the "tax_no" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableTaxNo(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetTaxNo(*v)
	}
	return _c
}

// SetRecipientEmail sets the "recipient_email" field.
func (_c *InvoiceRequestCreate) SetRecipientEmail(v string) *InvoiceRequestCreate {
	_c.mutation.SetRecipientEmail(v)
	return _c
}

// SetNillableRecipientEmail sets the "recipient_email" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableRecipientEmail(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetRecipientEmail(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *InvoiceRequestCreate) SetRemark(v string) *InvoiceRequestCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableRemark(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *InvoiceRequestCreate) SetStatus(v string) *InvoiceRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableStatus(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRejectReason sets the "reject_reason" field.
func (_c *InvoiceRequestCreate) SetRejectReason(v string) *InvoiceRequestCreate {
	_c.mutation.SetRejectReason(v)
	return _c
}

// SetNillableRejectReason sets the "reject_reason" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableRejectReason(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetRejectReason(*v)
	}
	return _c
}

// SetInvoiceNo sets the "invoice_no" field.
func (_c *InvoiceRequestCreate) SetInvoiceNo(v string) *InvoiceRequestCreate {
	_c.mutation.SetInvoiceNo(v)
	return _c
}

// SetNillableInvoiceNo sets the "invoice_no" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableInvoiceNo(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetInvoiceNo(*v)
	}
	return _c
}

// SetInvoiceFilePath sets the "invoice_file_path" field.
func (_c *InvoiceRequestCreate) SetInvoiceFilePath(v string) *InvoiceRequestCreate {
	_c.mutation.SetInvoiceFilePath(v)
	return _c
}

// SetNillableInvoiceFilePath sets the "invoice_file_path" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableInvoiceFilePath(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetInvoiceFilePath(*v)
	}
	return _c
}

// SetIssuedAt sets the "issued_at" field.
func (_c *InvoiceRequestCreate) SetIssuedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetIssuedAt(v)
	return _c
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableIssuedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetIssuedAt(*v)
	}
	return _c
}

// SetProcessedBy sets the "processed_by" field.
func (_c *InvoiceRequestCreate) SetProcessedBy(v int64) *InvoiceRequestCreate {
	_c.mutation.SetProcessedBy(v)
	return _c
}

// SetNillableProcessedBy sets the "processed_by" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableProcessedBy(v *int64) *InvoiceRequestCreate {
	if v != nil {
		_c.SetProcessedBy(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *InvoiceRequestCreate) SetUser(v *User) *InvoiceRequestCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the InvoiceRequestMutation object of the builder.
func (_c *InvoiceRequestCreate) Mutation() *InvoiceRequestMutation {
	return _c.mutation
}

// Save creates the InvoiceRequest in the database.
func (_c *InvoiceRequestCreate) Save(ctx context.Context) (*InvoiceRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceRequestCreate) SaveX(ctx context.Context) *InvoiceRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceRequestCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoicerequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := invoicerequest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.RedeemCodeIds(); !ok {
		v := invoicerequest.DefaultRedeemCodeIds
		_c.mutation.SetRedeemCodeIds(v)
	}
	if _, ok := _c.mutation.InvoiceType(); !ok {
		v := invoicerequest.DefaultInvoiceType
		_c.mutation.SetInvoiceType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := invoicerequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceRequestCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceRequest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InvoiceRequest.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InvoiceRequest.user_id"`)}
	}
	if _, ok := _c.mutation.PaymentOrderIds(); !ok {
		return &ValidationError{Name: "payment_order_ids", err: errors.New(`ent: missing required field "InvoiceRequest.payment_order_ids"`)}
	}
	if _, ok := _c.mutation.RedeemCodeIds(); !ok {
		return &ValidationError{Name: "redeem_code_ids", err: errors.New(`ent: missing required field "InvoiceRequest.redeem_code_ids"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "InvoiceRequest.amount"`)}
	}
	if _, ok := _c.mutation.InvoiceType(); !ok {
		return &ValidationError{Name: "invoice_type", err: errors.New(`ent: missing required field "InvoiceRequest.invoice_type"`)}
	}
	if v, ok := _c.mutation.InvoiceType(); ok {
		if err := invoicerequest.InvoiceTypeValidator(v); err != nil {
			return &ValidationError{Name: "invoice_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.invoice_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "InvoiceRequest.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := invoicerequest.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaxNo(); ok {
		if err := invoicerequest.TaxNoValidator(v); err != nil {
			return &ValidationError{Name: "tax_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.tax_no": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RecipientEmail(); ok {
		if err := invoicerequest.RecipientEmailValidator(v); err != nil {
			return &ValidationError{Name: "recipient_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.recipient_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "InvoiceRequest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := invoicerequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.InvoiceNo(); ok {
		if err := invoicerequest.InvoiceNoValidator(v); err != nil {
			return &ValidationError{Name: "invoice_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.invoice_no": %w`, err)}
		}
	}
	if v, ok := _c.mutation.InvoiceFilePath(); ok {
		if err := invoicerequest.InvoiceFilePathValidator(v); err != nil {
			return &ValidationError{Name: "invoice_file_path", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.invoice_file_path": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "InvoiceRequest.user"`)}
	}
	return nil
}

func (_c *InvoiceRequestCreate) sqlSave(ctx context.Context) (*InvoiceRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceRequestCreate) createSpec() (*InvoiceRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoicerequest.Table, sqlgraph.NewFieldSpec(invoicerequest.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoicerequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invoicerequest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PaymentOrderIds(); ok {
		_spec.SetField(invoicerequest.FieldPaymentOrderIds, field.TypeJSON, value)
		_node.PaymentOrderIds = value
	}
	if value, ok := _c.mutation.RedeemCodeIds(); ok {
		_spec.SetField(invoicerequest.FieldRedeemCodeIds, field.TypeJSON, value)
		_node.RedeemCodeIds = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(invoicerequest.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.InvoiceType(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceType, field.TypeString, value)
		_node.InvoiceType = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(invoicerequest.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.TaxNo(); ok {
		_spec.SetField(invoicerequest.FieldTaxNo, field.TypeString, value)
		_node.TaxNo = &value
	}
	if value, ok := _c.mutation.RecipientEmail(); ok {
		_spec.SetField(invoicerequest.FieldRecipientEmail, field.TypeString, value)
		_node.RecipientEmail = &value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(invoicerequest.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(invoicerequest.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RejectReason(); ok {
		_spec.SetField(invoicerequest.FieldRejectReason, field.TypeString, value)
		_node.RejectReason = &value
	}
	if value, ok := _c.mutation.InvoiceNo(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceNo, field.TypeString, value)
		_node.InvoiceNo = &value
	}
	if value, ok := _c.mutation.InvoiceFilePath(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceFilePath, field.TypeString, value)
		_node.InvoiceFilePath = &value
	}
	if value, ok := _c.mutation.IssuedAt(); ok {
		_spec.SetField(invoicerequest.FieldIssuedAt, field.TypeTime, value)
		_node.IssuedAt = &value
	}
	if value, ok := _c.mutation.ProcessedBy(); ok {
		_spec.SetField(invoicerequest.FieldProcessedBy, field.TypeInt64, value)
		_node.ProcessedBy = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoicerequest.UserTable,
			Columns: []string{invoicerequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceRequest.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceRequestUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceRequestCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceRequestUpsertOne {
	_c.conflict = opts
	return &InvoiceRequestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceRequestCreate) OnConflictColumns(columns ...string) *InvoiceRequestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceRequestUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceRequestUpsertOne is the builder for "upsert"-ing
	//  one InvoiceRequest node.
	InvoiceRequestUpsertOne struct {
		create *InvoiceRequestCreate
	}

	// InvoiceRequestUpsert is the "OnConflict" setter.
	InvoiceRequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceRequestUpsert) SetUpdatedAt(v time.Time) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateUpdatedAt() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceRequestUpsert) SetUserID(v int64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateUserID() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldUserID)
	return u
}

// SetPaymentOrderIds sets the "payment_order_ids" field.
func (u *InvoiceRequestUpsert) SetPaymentOrderIds(v []int64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldPaymentOrderIds, v)
	return u
}

// UpdatePaymentOrderIds sets the "payment_order_ids" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdatePaymentOrderIds() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldPaymentOrderIds)
	return u
}

// SetRedeemCodeIds sets the "redeem_code_ids" field.
func (u *InvoiceRequestUpsert) SetRedeemCodeIds(v []int64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldRedeemCodeIds, v)
	return u
}

// UpdateRedeemCodeIds sets the "redeem_code_ids" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateRedeemCodeIds() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldRedeemCodeIds)
	return u
}

// SetAmount sets the "amount" field.
func (u *InvoiceRequestUpsert) SetAmount(v float64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateAmount() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceRequestUpsert) AddAmount(v float64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldAmount, v)
	return u
}

// SetInvoiceType sets the "invoice_type" field.
func (u *InvoiceRequestUpsert) SetInvoiceType(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldInvoiceType, v)
	return u
}

// UpdateInvoiceType sets the "invoice_type" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateInvoiceType() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldInvoiceType)
	return u
}

// SetTitle sets the "title" field.
func (u *InvoiceRequestUpsert) SetTitle(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateTitle() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldTitle)
	return u
}

// SetTaxNo sets the "tax_no" field.
func (u *InvoiceRequestUpsert) SetTaxNo(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldTaxNo, v)
	return u
}

// UpdateTaxNo sets the "tax_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateTaxNo() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldTaxNo)
	return u
}

// ClearTaxNo clears the value of the "tax_no" field.
func (u *InvoiceRequestUpsert) ClearTaxNo() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldTaxNo)
	return u
}

// SetRecipientEmail sets the "recipient_email" field.
func (u *InvoiceRequestUpsert) SetRecipientEmail(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldRecipientEmail, v)
	return u
}

// UpdateRecipientEmail sets the "recipient_email" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateRecipientEmail() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldRecipientEmail)
	return u
}

// ClearRecipientEmail clears the value of the "recipient_email" field.
func (u *InvoiceRequestUpsert) ClearRecipientEmail() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldRecipientEmail)
	return u
}

// SetRemark sets the "remark" field.
func (u *InvoiceRequestUpsert) SetRemark(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateRemark() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *InvoiceRequestUpsert) ClearRemark() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldRemark)
	return u
}

// SetStatus sets the "status" field.
func (u *InvoiceRequestUpsert) SetStatus(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateStatus() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldStatus)
	return u
}

// SetRejectReason sets the "reject_reason" field.
func (u *InvoiceRequestUpsert) SetRejectReason(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldRejectReason, v)
	return u
}

// UpdateRejectReason sets the "reject_reason" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateRejectReason() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldRejectReason)
	return u
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (u *InvoiceRequestUpsert) ClearRejectReason() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldRejectReason)
	return u
}

// SetInvoiceNo sets the "invoice_no" field.
func (u *InvoiceRequestUpsert) SetInvoiceNo(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldInvoiceNo, v)
	return u
}

// UpdateInvoiceNo sets the "invoice_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateInvoiceNo() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldInvoiceNo)
	return u
}

// ClearInvoiceNo clears the value of the "invoice_no" field.
func (u *InvoiceRequestUpsert) ClearInvoiceNo() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldInvoiceNo)
	return u
}

// SetInvoiceFilePath sets the "invoice_file_path" field.
func (u *InvoiceRequestUpsert) SetInvoiceFilePath(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldInvoiceFilePath, v)
	return u
}

// UpdateInvoiceFilePath sets the "invoice_file_path" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateInvoiceFilePath() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldInvoiceFilePath)
	return u
}

// ClearInvoiceFilePath clears the value of the "invoice_file_path" field.
func (u *InvoiceRequestUpsert) ClearInvoiceFilePath() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldInvoiceFilePath)
	return u
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceRequestUpsert) SetIssuedAt(v time.Time) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldIssuedAt, v)
	return u
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateIssuedAt() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldIssuedAt)
	return u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceRequestUpsert) ClearIssuedAt() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldIssuedAt)
	return u
}

// SetProcessedBy sets the "processed_by" field.
func (u *InvoiceRequestUpsert) SetProcessedBy(v int64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldProcessedBy, v)
	return u
}

// UpdateProcessedBy sets the "processed_by" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateProcessedBy() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldProcessedBy)
	return u
}

// AddProcessedBy adds v to the "processed_by" field.
func (u *InvoiceRequestUpsert) AddProcessedBy(v int64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldProcessedBy, v)
	return u
}

// ClearProcessedBy clears the value of the "processed_by" field.
func (u *InvoiceRequestUpsert) ClearProcessedBy() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldProcessedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceRequestUpsertOne) UpdateNewValues() *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoicerequest.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceRequestUpsertOne) Ignore() *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceRequestUpsertOne) DoNothing() *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceRequestCreate.OnConflict
// documentation for more info.
func (u *InvoiceRequestUpsertOne) Update(set func(*InvoiceRequestUpsert)) *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceRequestUpsertOne) SetUpdatedAt(v time.Time) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateUpdatedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *InvoiceRequestUpsertOne) SetUserID(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateUserID() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUserID()
	})
}

// SetPaymentOrderIds sets the "payment_order_ids" field.
func (u *InvoiceRequestUpsertOne) SetPaymentOrderIds(v []int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetPaymentOrderIds(v)
	})
}

// UpdatePaymentOrderIds sets the "payment_order_ids" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdatePaymentOrderIds() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdatePaymentOrderIds()
	})
}

// SetRedeemCodeIds sets the "redeem_code_ids" field.
func (u *InvoiceRequestUpsertOne) SetRedeemCodeIds(v []int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRedeemCodeIds(v)
	})
}

// UpdateRedeemCodeIds sets the "redeem_code_ids" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateRedeemCodeIds() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRedeemCodeIds()
	})
}

// SetAmount sets the "amount" field.
func (u *InvoiceRequestUpsertOne) SetAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceRequestUpsertOne) AddAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateAmount() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateAmount()
	})
}

// SetInvoiceType sets the "invoice_type" field.
func (u *InvoiceRequestUpsertOne) SetInvoiceType(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceType(v)
	})
}

// UpdateInvoiceType sets the "invoice_type" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateInvoiceType() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceType()
	})
}

// SetTitle sets the "title" field.
func (u *InvoiceRequestUpsertOne) SetTitle(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateTitle() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTitle()
	})
}

// SetTaxNo sets the "tax_no" field.
func (u *InvoiceRequestUpsertOne) SetTaxNo(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTaxNo(v)
	})
}

// UpdateTaxNo sets the "tax_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateTaxNo() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTaxNo()
	})
}

// ClearTaxNo clears the value of the "tax_no" field.
func (u *InvoiceRequestUpsertOne) ClearTaxNo() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearTaxNo()
	})
}

// SetRecipientEmail sets the "recipient_email" field.
func (u *InvoiceRequestUpsertOne) SetRecipientEmail(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRecipientEmail(v)
	})
}

// UpdateRecipientEmail sets the "recipient_email" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateRecipientEmail() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRecipientEmail()
	})
}

// ClearRecipientEmail clears the value of the "recipient_email" field.
func (u *InvoiceRequestUpsertOne) ClearRecipientEmail() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearRecipientEmail()
	})
}

// SetRemark sets the "remark" field.
func (u *InvoiceRequestUpsertOne) SetRemark(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateRemark() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *InvoiceRequestUpsertOne) ClearRemark() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearRemark()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceRequestUpsertOne) SetStatus(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateStatus() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetRejectReason sets the "reject_reason" field.
func (u *InvoiceRequestUpsertOne) SetRejectReason(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRejectReason(v)
	})
}

// UpdateRejectReason sets the "reject_reason" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateRejectReason() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRejectReason()
	})
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (u *InvoiceRequestUpsertOne) ClearRejectReason() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearRejectReason()
	})
}

// SetInvoiceNo sets the "invoice_no" field.
func (u *InvoiceRequestUpsertOne) SetInvoiceNo(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceNo(v)
	})
}

// UpdateInvoiceNo sets the "invoice_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateInvoiceNo() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceNo()
	})
}

// ClearInvoiceNo clears the value of the "invoice_no" field.
func (u *InvoiceRequestUpsertOne) ClearInvoiceNo() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearInvoiceNo()
	})
}

// SetInvoiceFilePath sets the "invoice_file_path" field.
func (u *InvoiceRequestUpsertOne) SetInvoiceFilePath(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceFilePath(v)
	})
}

// UpdateInvoiceFilePath sets the "invoice_file_path" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateInvoiceFilePath() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceFilePath()
	})
}

// ClearInvoiceFilePath clears the value of the "invoice_file_path" field.
func (u *InvoiceRequestUpsertOne) ClearInvoiceFilePath() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearInvoiceFilePath()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceRequestUpsertOne) SetIssuedAt(v time.Time) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateIssuedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateIssuedAt()
	})
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceRequestUpsertOne) ClearIssuedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearIssuedAt()
	})
}

// SetProcessedBy sets the "processed_by" field.
func (u *InvoiceRequestUpsertOne) SetProcessedBy(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetProcessedBy(v)
	})
}

// AddProcessedBy adds v to the "processed_by" field.
func (u *InvoiceRequestUpsertOne) AddProcessedBy(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddProcessedBy(v)
	})
}

// UpdateProcessedBy sets the "processed_by" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateProcessedBy() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateProcessedBy()
	})
}

// ClearProcessedBy clears the value of the "processed_by" field.
func (u *InvoiceRequestUpsertOne) ClearProcessedBy() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearProcessedBy()
	})
}

// Exec executes the query.
func (u *InvoiceRequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceRequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceRequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceRequestUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceRequestUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceRequestCreateBulk is the builder for creating many InvoiceRequest entities in bulk.
type InvoiceRequestCreateBulk struct {
	config
	err      error
	builders []*InvoiceRequestCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceRequest entities in the database.
func (_c *InvoiceRequestCreateBulk) Save(ctx context.Context) ([]*InvoiceRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceRequestCreateBulk) SaveX(ctx context.Context) []*InvoiceRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceRequest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceRequestUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceRequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceRequestUpsertBulk {
	_c.conflict = opts
	return &InvoiceRequestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceRequestCreateBulk) OnConflictColumns(columns ...string) *InvoiceRequestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceRequestUpsertBulk{
		create: _c,
	}
}

// InvoiceRequestUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceRequest nodes.
type InvoiceRequestUpsertBulk struct {
	create *InvoiceRequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceRequestUpsertBulk) UpdateNewValues() *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoicerequest.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceRequestUpsertBulk) Ignore() *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceRequestUpsertBulk) DoNothing() *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceRequestCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceRequestUpsertBulk) Update(set func(*InvoiceRequestUpsert)) *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceRequestUpsertBulk) SetUpdatedAt(v time.Time) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateUpdatedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *InvoiceRequestUpsertBulk) SetUserID(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateUserID() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUserID()
	})
}

// SetPaymentOrderIds sets the "payment_order_ids" field.
func (u *InvoiceRequestUpsertBulk) SetPaymentOrderIds(v []int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetPaymentOrderIds(v)
	})
}

// UpdatePaymentOrderIds sets the "payment_order_ids" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdatePaymentOrderIds() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdatePaymentOrderIds()
	})
}

// SetRedeemCodeIds sets the "redeem_code_ids" field.
func (u *InvoiceRequestUpsertBulk) SetRedeemCodeIds(v []int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRedeemCodeIds(v)
	})
}

// UpdateRedeemCodeIds sets the "redeem_code_ids" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateRedeemCodeIds() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRedeemCodeIds()
	})
}

// SetAmount sets the "amount" field.
func (u *InvoiceRequestUpsertBulk) SetAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceRequestUpsertBulk) AddAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateAmount() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateAmount()
	})
}

// SetInvoiceType sets the "invoice_type" field.
func (u *InvoiceRequestUpsertBulk) SetInvoiceType(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceType(v)
	})
}

// UpdateInvoiceType sets the "invoice_type" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateInvoiceType() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceType()
	})
}

// SetTitle sets the "title" field.
func (u *InvoiceRequestUpsertBulk) SetTitle(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateTitle() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTitle()
	})
}

// SetTaxNo sets the "tax_no" field.
func (u *InvoiceRequestUpsertBulk) SetTaxNo(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTaxNo(v)
	})
}

// UpdateTaxNo sets the "tax_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateTaxNo() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTaxNo()
	})
}

// ClearTaxNo clears the value of the "tax_no" field.
func (u *InvoiceRequestUpsertBulk) ClearTaxNo() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearTaxNo()
	})
}

// SetRecipientEmail sets the "recipient_email" field.
func (u *InvoiceRequestUpsertBulk) SetRecipientEmail(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRecipientEmail(v)
	})
}

// UpdateRecipientEmail sets the "recipient_email" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateRecipientEmail() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRecipientEmail()
	})
}

// ClearRecipientEmail clears the value of the "recipient_email" field.
func (u *InvoiceRequestUpsertBulk) ClearRecipientEmail() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearRecipientEmail()
	})
}

// SetRemark sets the "remark" field.
func (u *InvoiceRequestUpsertBulk) SetRemark(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateRemark() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *InvoiceRequestUpsertBulk) ClearRemark() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearRemark()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceRequestUpsertBulk) SetStatus(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateStatus() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetRejectReason sets the "reject_reason" field.
func (u *InvoiceRequestUpsertBulk) SetRejectReason(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRejectReason(v)
	})
}

// UpdateRejectReason sets the "reject_reason" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateRejectReason() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRejectReason()
	})
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (u *InvoiceRequestUpsertBulk) ClearRejectReason() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearRejectReason()
	})
}

// SetInvoiceNo sets the "invoice_no" field.
func (u *InvoiceRequestUpsertBulk) SetInvoiceNo(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceNo(v)
	})
}

// UpdateInvoiceNo sets the "invoice_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateInvoiceNo() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceNo()
	})
}

// ClearInvoiceNo clears the value of the "invoice_no" field.
func (u *InvoiceRequestUpsertBulk) ClearInvoiceNo() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearInvoiceNo()
	})
}

// SetInvoiceFilePath sets the "invoice_file_path" field.
func (u *InvoiceRequestUpsertBulk) SetInvoiceFilePath(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceFilePath(v)
	})
}

// UpdateInvoiceFilePath sets the "invoice_file_path" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateInvoiceFilePath() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceFilePath()
	})
}

// ClearInvoiceFilePath clears the value of the "invoice_file_path" field.
func (u *InvoiceRequestUpsertBulk) ClearInvoiceFilePath() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearInvoiceFilePath()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceRequestUpsertBulk) SetIssuedAt(v time.Time) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateIssuedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateIssuedAt()
	})
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceRequestUpsertBulk) ClearIssuedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearIssuedAt()
	})
}

// SetProcessedBy sets the "processed_by" field.
func (u *InvoiceRequestUpsertBulk) SetProcessedBy(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetProcessedBy(v)
	})
}

// AddProcessedBy adds v to the "processed_by" field.
func (u *InvoiceRequestUpsertBulk) AddProcessedBy(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddProcessedBy(v)
	})
}

// UpdateProcessedBy sets the "processed_by" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateProcessedBy() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateProcessedBy()
	})
}

// ClearProcessedBy clears the value of the "processed_by" field.
func (u *InvoiceRequestUpsertBulk) ClearProcessedBy() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearProcessedBy()
	})
}

// Exec executes the query.
func (u *InvoiceRequestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceRequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceRequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceRequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
