// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/invoicerequest"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceRequest is the model entity for the InvoiceRequest schema.
type InvoiceRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// PaymentOrderIds holds the value of the "payment_order_ids" field.
	PaymentOrderIds []int64 `json:"payment_order_ids,omitempty"`
	// RedeemCodeIds holds the value of the "redeem_code_ids" field.
	RedeemCodeIds []int64 `json:"redeem_code_ids,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// InvoiceType holds the value of the "invoice_type" field.
	InvoiceType string `json:"invoice_type,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// TaxNo holds the value of the "tax_no" field.
	TaxNo *string `json:"tax_no,omitempty"`
	// RecipientEmail holds the value of the "recipient_email" field.
	RecipientEmail *string `json:"recipient_email,omitempty"`
	// Remark holds the value of the "remark" field.
	Remark *string `json:"remark,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// RejectReason holds the value of the "reject_reason" field.
	RejectReason *string `json:"reject_reason,omitempty"`
	// InvoiceNo holds the value of the "invoice_no" field.
	InvoiceNo *string `json:"invoice_no,omitempty"`
	// InvoiceFilePath holds the value of the "invoice_file_path" field.
	InvoiceFilePath *string `json:"invoice_file_path,omitempty"`
	// IssuedAt holds the value of the "issued_at" field.
	IssuedAt *time.Time `json:"issued_at,omitempty"`
	// ProcessedBy holds the value of the "processed_by" field.
	ProcessedBy *int64 `json:"processed_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InvoiceRequestQuery when eager-loading is set.
	Edges        InvoiceRequestEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InvoiceRequestEdges holds the relations/edges for other nodes in the graph.
type InvoiceRequestEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvoiceRequestEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvoiceRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoicerequest.FieldPaymentOrderIds, invoicerequest.FieldRedeemCodeIds:
			values[i] = new([]byte)
		case invoicerequest.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case invoicerequest.FieldID, invoicerequest.FieldUserID, invoicerequest.FieldProcessedBy:
			values[i] = new(sql.NullInt64)
		case invoicerequest.FieldInvoiceType, invoicerequest.FieldTitle, invoicerequest.FieldTaxNo, invoicerequest.FieldRecipientEmail, invoicerequest.FieldRemark, invoicerequest.FieldStatus, invoicerequest.FieldRejectReason, invoicerequest.FieldInvoiceNo, invoicerequest.FieldInvoiceFilePath:
			values[i] = new(sql.NullString)
		case invoicerequest.FieldCreatedAt, invoicerequest.FieldUpdatedAt, invoicerequest.FieldIssuedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvoiceRequest fields.
func (_m *InvoiceRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoicerequest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case invoicerequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case invoicerequest.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case invoicerequest.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case invoicerequest.FieldPaymentOrderIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payment_order_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PaymentOrderIds); err != nil {
					return fmt.Errorf("unmarshal field payment_order_ids: %w", err)
				}
			}
		case invoicerequest.FieldRedeemCodeIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field redeem_code_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RedeemCodeIds); err != nil {
					return fmt.Errorf("unmarshal field redeem_code_ids: %w", err)
				}
			}
		case invoicerequest.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case invoicerequest.FieldInvoiceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_type", values[i])
			} else if value.Valid {
				_m.InvoiceType = value.String
			}
		case invoicerequest.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case invoicerequest.FieldTaxNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tax_no", values[i])
			} else if value.Valid {
				_m.TaxNo = new(string)
				*_m.TaxNo = value.String
			}
		case invoicerequest.FieldRecipientEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recipient_email", values[i])
			} else if value.Valid {
				_m.RecipientEmail = new(string)
				*_m.RecipientEmail = value.String
			}
		case invoicerequest.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = new(string)
				*_m.Remark = value.String
			}
		case invoicerequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case invoicerequest.FieldRejectReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reject_reason", values[i])
			} else if value.Valid {
				_m.RejectReason = new(string)
				*_m.RejectReason = value.String
			}
		case invoicerequest.FieldInvoiceNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_no", values[i])
			} else if value.Valid {
				_m.InvoiceNo = new(string)
				*_m.InvoiceNo = value.String
			}
		case invoicerequest.FieldInvoiceFilePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_file_path", values[i])
			} else if value.Valid {
				_m.InvoiceFilePath = new(string)
				*_m.InvoiceFilePath = value.String
			}
		case invoicerequest.FieldIssuedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field issued_at", values[i])
			} else if value.Valid {
				_m.IssuedAt = new(time.Time)
				*_m.IssuedAt = value.Time
			}
		case invoicerequest.FieldProcessedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field processed_by", values[i])
			} else if value.Valid {
				_m.ProcessedBy = new(int64)
				*_m.ProcessedBy = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvoiceRequest.
// This includes values selected through modifiers, order, etc.
func (_m *InvoiceRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the InvoiceRequest entity.
func (_m *InvoiceRequest) QueryUser() *UserQuery {
	return NewInvoiceRequestClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this InvoiceRequest.
// Note that you need to call InvoiceRequest.Unwrap() before calling this method if this InvoiceRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InvoiceRequest) Update() *InvoiceRequestUpdateOne {
	return NewInvoiceRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InvoiceRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InvoiceRequest) Unwrap() *InvoiceRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvoiceRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InvoiceRequest) String() string {
	var builder strings.Builder
	builder.WriteString("InvoiceRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("payment_order_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaymentOrderIds))
	builder.WriteString(", ")
	builder.WriteString("redeem_code_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.RedeemCodeIds))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("invoice_type=")
	builder.WriteString(_m.InvoiceType)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.TaxNo; v != nil {
		builder.WriteString("tax_no=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RecipientEmail; v != nil {
		builder.WriteString("recipient_email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Remark; v != nil {
		builder.WriteString("remark=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.RejectReason; v != nil {
		builder.WriteString("reject_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.InvoiceNo; v != nil {
		builder.WriteString("invoice_no=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.InvoiceFilePath; v != nil {
		builder.WriteString("invoice_file_path=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IssuedAt; v != nil {
		builder.WriteString("issued_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ProcessedBy; v != nil {
		builder.WriteString("processed_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// InvoiceRequests is a parsable slice of InvoiceRequest.
type InvoiceRequests []*InvoiceRequest
