// Code generated by ent, DO NOT EDIT.

package invoicerequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUserID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldAmount, v))
}

// InvoiceType applies equality check predicate on the "invoice_type" field. It's identical to InvoiceTypeEQ.
func InvoiceType(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldInvoiceType, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTitle, v))
}

// TaxNo applies equality check predicate on the "tax_no" field. It's identical to TaxNoEQ.
func TaxNo(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTaxNo, v))
}

// RecipientEmail applies equality check predicate on the "recipient_email" field. It's identical to RecipientEmailEQ.
func RecipientEmail(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldRecipientEmail, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldRemark, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldStatus, v))
}

// RejectReason applies equality check predicate on the "reject_reason" field. It's identical to RejectReasonEQ.
func RejectReason(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldRejectReason, v))
}

// InvoiceNo applies equality check predicate on the "invoice_no" field. It's identical to InvoiceNoEQ.
func InvoiceNo(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldInvoiceNo, v))
}

// InvoiceFilePath applies equality check predicate on the "invoice_file_path" field. It's identical to InvoiceFilePathEQ.
func InvoiceFilePath(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldInvoiceFilePath, v))
}

// IssuedAt applies equality check predicate on the "issued_at" field. It's identical to IssuedAtEQ.
func IssuedAt(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldIssuedAt, v))
}

// ProcessedBy applies equality check predicate on the "processed_by" field. It's identical to ProcessedByEQ.
func ProcessedBy(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldProcessedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldUserID, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldAmount, v))
}

// InvoiceTypeEQ applies the EQ predicate on the "invoice_type" field.
func InvoiceTypeEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldInvoiceType, v))
}

// InvoiceTypeNEQ applies the NEQ predicate on the "invoice_type" field.
func InvoiceTypeNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldInvoiceType, v))
}

// InvoiceTypeIn applies the In predicate on the "invoice_type" field.
func InvoiceTypeIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldInvoiceType, vs...))
}

// InvoiceTypeNotIn applies the NotIn predicate on the "invoice_type" field.
func InvoiceTypeNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldInvoiceType, vs...))
}

// InvoiceTypeGT applies the GT predicate on the "invoice_type" field.
func InvoiceTypeGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldInvoiceType, v))
}

// InvoiceTypeGTE applies the GTE predicate on the "invoice_type" field.
func InvoiceTypeGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldInvoiceType, v))
}

// InvoiceTypeLT applies the LT predicate on the "invoice_type" field.
func InvoiceTypeLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldInvoiceType, v))
}

// InvoiceTypeLTE applies the LTE predicate on the "invoice_type" field.
func InvoiceTypeLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldInvoiceType, v))
}

// InvoiceTypeContains applies the Contains predicate on the "invoice_type" field.
func InvoiceTypeContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldInvoiceType, v))
}

// InvoiceTypeHasPrefix applies the HasPrefix predicate on the "invoice_type" field.
func InvoiceTypeHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldInvoiceType, v))
}

// InvoiceTypeHasSuffix applies the HasSuffix predicate on the "invoice_type" field.
func InvoiceTypeHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldInvoiceType, v))
}

// InvoiceTypeEqualFold applies the EqualFold predicate on the "invoice_type" field.
func InvoiceTypeEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldInvoiceType, v))
}

// InvoiceTypeContainsFold applies the ContainsFold predicate on the "invoice_type" field.
func InvoiceTypeContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldInvoiceType, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldTitle, v))
}

// TaxNoEQ applies the EQ predicate on the "tax_no" field.
func TaxNoEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTaxNo, v))
}

// TaxNoNEQ applies the NEQ predicate on the "tax_no" field.
func TaxNoNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldTaxNo, v))
}

// TaxNoIn applies the In predicate on the "tax_no" field.
func TaxNoIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldTaxNo, vs...))
}

// TaxNoNotIn applies the NotIn predicate on the "tax_no" field.
func TaxNoNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldTaxNo, vs...))
}

// TaxNoGT applies the GT predicate on the "tax_no" field.
func TaxNoGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldTaxNo, v))
}

// TaxNoGTE applies the GTE predicate on the "tax_no" field.
func TaxNoGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldTaxNo, v))
}

// TaxNoLT applies the LT predicate on the "tax_no" field.
func TaxNoLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldTaxNo, v))
}

// TaxNoLTE applies the LTE predicate on the "tax_no" field.
func TaxNoLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldTaxNo, v))
}

// TaxNoContains applies the Contains predicate on the "tax_no" field.
func TaxNoContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldTaxNo, v))
}

// TaxNoHasPrefix applies the HasPrefix predicate on the "tax_no" field.
func TaxNoHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldTaxNo, v))
}

// TaxNoHasSuffix applies the HasSuffix predicate on the "tax_no" field.
func TaxNoHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldTaxNo, v))
}

// TaxNoIsNil applies the IsNil predicate on the "tax_no" field.
func TaxNoIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldTaxNo))
}

// TaxNoNotNil applies the NotNil predicate on the "tax_no" field.
func TaxNoNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldTaxNo))
}

// TaxNoEqualFold applies the EqualFold predicate on the "tax_no" field.
func TaxNoEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldTaxNo, v))
}

// TaxNoContainsFold applies the ContainsFold predicate on the "tax_no" field.
func TaxNoContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldTaxNo, v))
}

// RecipientEmailEQ applies the EQ predicate on the "recipient_email" field.
func RecipientEmailEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldRecipientEmail, v))
}

// RecipientEmailNEQ applies the NEQ predicate on the "recipient_email" field.
func RecipientEmailNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldRecipientEmail, v))
}

// RecipientEmailIn applies the In predicate on the "recipient_email" field.
func RecipientEmailIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldRecipientEmail, vs...))
}

// RecipientEmailNotIn applies the NotIn predicate on the "recipient_email" field.
func RecipientEmailNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldRecipientEmail, vs...))
}

// RecipientEmailGT applies the GT predicate on the "recipient_email" field.
func RecipientEmailGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldRecipientEmail, v))
}

// RecipientEmailGTE applies the GTE predicate on the "recipient_email" field.
func RecipientEmailGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldRecipientEmail, v))
}

// RecipientEmailLT applies the LT predicate on the "recipient_email" field.
func RecipientEmailLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldRecipientEmail, v))
}

// RecipientEmailLTE applies the LTE predicate on the "recipient_email" field.
func RecipientEmailLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldRecipientEmail, v))
}

// RecipientEmailContains applies the Contains predicate on the "recipient_email" field.
func RecipientEmailContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldRecipientEmail, v))
}

// RecipientEmailHasPrefix applies the HasPrefix predicate on the "recipient_email" field.
func RecipientEmailHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldRecipientEmail, v))
}

// RecipientEmailHasSuffix applies the HasSuffix predicate on the "recipient_email" field.
func RecipientEmailHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldRecipientEmail, v))
}

// RecipientEmailIsNil applies the IsNil predicate on the "recipient_email" field.
func RecipientEmailIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldRecipientEmail))
}

// RecipientEmailNotNil applies the NotNil predicate on the "recipient_email" field.
func RecipientEmailNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldRecipientEmail))
}

// RecipientEmailEqualFold applies the EqualFold predicate on the "recipient_email" field.
func RecipientEmailEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldRecipientEmail, v))
}

// RecipientEmailContainsFold applies the ContainsFold predicate on the "recipient_email" field.
func RecipientEmailContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldRecipientEmail, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldRemark, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldStatus, v))
}

// RejectReasonEQ applies the EQ predicate on the "reject_reason" field.
func RejectReasonEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldRejectReason, v))
}

// RejectReasonNEQ applies the NEQ predicate on the "reject_reason" field.
func RejectReasonNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldRejectReason, v))
}

// RejectReasonIn applies the In predicate on the "reject_reason" field.
func RejectReasonIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldRejectReason, vs...))
}

// RejectReasonNotIn applies the NotIn predicate on the "reject_reason" field.
func RejectReasonNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldRejectReason, vs...))
}

// RejectReasonGT applies the GT predicate on the "reject_reason" field.
func RejectReasonGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldRejectReason, v))
}

// RejectReasonGTE applies the GTE predicate on the "reject_reason" field.
func RejectReasonGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldRejectReason, v))
}

// RejectReasonLT applies the LT predicate on the "reject_reason" field.
func RejectReasonLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldRejectReason, v))
}

// RejectReasonLTE applies the LTE predicate on the "reject_reason" field.
func RejectReasonLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldRejectReason, v))
}

// RejectReasonContains applies the Contains predicate on the "reject_reason" field.
func RejectReasonContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldRejectReason, v))
}

// RejectReasonHasPrefix applies the HasPrefix predicate on the "reject_reason" field.
func RejectReasonHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldRejectReason, v))
}

// RejectReasonHasSuffix applies the HasSuffix predicate on the "reject_reason" field.
func RejectReasonHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldRejectReason, v))
}

// RejectReasonIsNil applies the IsNil predicate on the "reject_reason" field.
func RejectReasonIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldRejectReason))
}

// RejectReasonNotNil applies the NotNil predicate on the "reject_reason" field.
func RejectReasonNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldRejectReason))
}

// RejectReasonEqualFold applies the EqualFold predicate on the "reject_reason" field.
func RejectReasonEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldRejectReason, v))
}

// RejectReasonContainsFold applies the ContainsFold predicate on the "reject_reason" field.
func RejectReasonContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldRejectReason, v))
}

// InvoiceNoEQ applies the EQ predicate on the "invoice_no" field.
func InvoiceNoEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldInvoiceNo, v))
}

// InvoiceNoNEQ applies the NEQ predicate on the "invoice_no" field.
func InvoiceNoNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldInvoiceNo, v))
}

// InvoiceNoIn applies the In predicate on the "invoice_no" field.
func InvoiceNoIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldInvoiceNo, vs...))
}

// InvoiceNoNotIn applies the NotIn predicate on the "invoice_no" field.
func InvoiceNoNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldInvoiceNo, vs...))
}

// InvoiceNoGT applies the GT predicate on the "invoice_no" field.
func InvoiceNoGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldInvoiceNo, v))
}

// InvoiceNoGTE applies the GTE predicate on the "invoice_no" field.
func InvoiceNoGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldInvoiceNo, v))
}

// InvoiceNoLT applies the LT predicate on the "invoice_no" field.
func InvoiceNoLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldInvoiceNo, v))
}

// InvoiceNoLTE applies the LTE predicate on the "invoice_no" field.
func InvoiceNoLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldInvoiceNo, v))
}

// InvoiceNoContains applies the Contains predicate on the "invoice_no" field.
func InvoiceNoContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldInvoiceNo, v))
}

// InvoiceNoHasPrefix applies the HasPrefix predicate on the "invoice_no" field.
func InvoiceNoHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldInvoiceNo, v))
}

// InvoiceNoHasSuffix applies the HasSuffix predicate on the "invoice_no" field.
func InvoiceNoHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldInvoiceNo, v))
}

// InvoiceNoIsNil applies the IsNil predicate on the "invoice_no" field.
func InvoiceNoIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldInvoiceNo))
}

// InvoiceNoNotNil applies the NotNil predicate on the "invoice_no" field.
func InvoiceNoNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldInvoiceNo))
}

// InvoiceNoEqualFold applies the EqualFold predicate on the "invoice_no" field.
func InvoiceNoEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldInvoiceNo, v))
}

// InvoiceNoContainsFold applies the ContainsFold predicate on the "invoice_no" field.
func InvoiceNoContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldInvoiceNo, v))
}

// InvoiceFilePathEQ applies the EQ predicate on the "invoice_file_path" field.
func InvoiceFilePathEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldInvoiceFilePath, v))
}

// InvoiceFilePathNEQ applies the NEQ predicate on the "invoice_file_path" field.
func InvoiceFilePathNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldInvoiceFilePath, v))
}

// InvoiceFilePathIn applies the In predicate on the "invoice_file_path" field.
func InvoiceFilePathIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldInvoiceFilePath, vs...))
}

// InvoiceFilePathNotIn applies the NotIn predicate on the "invoice_file_path" field.
func InvoiceFilePathNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldInvoiceFilePath, vs...))
}

// InvoiceFilePathGT applies the GT predicate on the "invoice_file_path" field.
func InvoiceFilePathGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldInvoiceFilePath, v))
}

// InvoiceFilePathGTE applies the GTE predicate on the "invoice_file_path" field.
func InvoiceFilePathGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldInvoiceFilePath, v))
}

// InvoiceFilePathLT applies the LT predicate on the "invoice_file_path" field.
func InvoiceFilePathLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldInvoiceFilePath, v))
}

// InvoiceFilePathLTE applies the LTE predicate on the "invoice_file_path" field.
func InvoiceFilePathLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldInvoiceFilePath, v))
}

// InvoiceFilePathContains applies the Contains predicate on the "invoice_file_path" field.
func InvoiceFilePathContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldInvoiceFilePath, v))
}

// InvoiceFilePathHasPrefix applies the HasPrefix predicate on the "invoice_file_path" field.
func InvoiceFilePathHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldInvoiceFilePath, v))
}

// InvoiceFilePathHasSuffix applies the HasSuffix predicate on the "invoice_file_path" field.
func InvoiceFilePathHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldInvoiceFilePath, v))
}

// InvoiceFilePathIsNil applies the IsNil predicate on the "invoice_file_path" field.
func InvoiceFilePathIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldInvoiceFilePath))
}

// InvoiceFilePathNotNil applies the NotNil predicate on the "invoice_file_path" field.
func InvoiceFilePathNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldInvoiceFilePath))
}

// InvoiceFilePathEqualFold applies the EqualFold predicate on the "invoice_file_path" field.
func InvoiceFilePathEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldInvoiceFilePath, v))
}

// InvoiceFilePathContainsFold applies the ContainsFold predicate on the "invoice_file_path" field.
func InvoiceFilePathContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldInvoiceFilePath, v))
}

// IssuedAtEQ applies the EQ predicate on the "issued_at" field.
func IssuedAtEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldIssuedAt, v))
}

// IssuedAtNEQ applies the NEQ predicate on the "issued_at" field.
func IssuedAtNEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldIssuedAt, v))
}

// IssuedAtIn applies the In predicate on the "issued_at" field.
func IssuedAtIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldIssuedAt, vs...))
}

// IssuedAtNotIn applies the NotIn predicate on the "issued_at" field.
func IssuedAtNotIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldIssuedAt, vs...))
}

// IssuedAtGT applies the GT predicate on the "issued_at" field.
func IssuedAtGT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldIssuedAt, v))
}

// IssuedAtGTE applies the GTE predicate on the "issued_at" field.
func IssuedAtGTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldIssuedAt, v))
}

// IssuedAtLT applies the LT predicate on the "issued_at" field.
func IssuedAtLT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldIssuedAt, v))
}

// IssuedAtLTE applies the LTE predicate on the "issued_at" field.
func IssuedAtLTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldIssuedAt, v))
}

// IssuedAtIsNil applies the IsNil predicate on the "issued_at" field.
func IssuedAtIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldIssuedAt))
}

// IssuedAtNotNil applies the NotNil predicate on the "issued_at" field.
func IssuedAtNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldIssuedAt))
}

// ProcessedByEQ applies the EQ predicate on the "processed_by" field.
func ProcessedByEQ(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldProcessedBy, v))
}

// ProcessedByNEQ applies the NEQ predicate on the "processed_by" field.
func ProcessedByNEQ(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldProcessedBy, v))
}

// ProcessedByIn applies the In predicate on the "processed_by" field.
func ProcessedByIn(vs ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldProcessedBy, vs...))
}

// ProcessedByNotIn applies the NotIn predicate on the "processed_by" field.
func ProcessedByNotIn(vs ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldProcessedBy, vs...))
}

// ProcessedByGT applies the GT predicate on the "processed_by" field.
func ProcessedByGT(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldProcessedBy, v))
}

// ProcessedByGTE applies the GTE predicate on the "processed_by" field.
func ProcessedByGTE(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldProcessedBy, v))
}

// ProcessedByLT applies the LT predicate on the "processed_by" field.
func ProcessedByLT(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldProcessedBy, v))
}

// ProcessedByLTE applies the LTE predicate on the "processed_by" field.
func ProcessedByLTE(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldProcessedBy, v))
}

// ProcessedByIsNil applies the IsNil predicate on the "processed_by" field.
func ProcessedByIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldProcessedBy))
}

// ProcessedByNotNil applies the NotNil predicate on the "processed_by" field.
func ProcessedByNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldProcessedBy))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceRequest) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceRequest) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceRequest) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.NotPredicates(p))
}
