export { arrow, actions, providers, note, layout, orbitArt, porcelainArt, prismArt, terminal, originalGoldArt as goldArt, originalGoldArt }

const arrow = '<span aria-hidden="true">↗</span>'
const symbol = '<svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M6 24V8h5l10 16h5V8M6 16h20" stroke="currentColor" stroke-width="2.4" stroke-linecap="square"/></svg>'
const brand = `<a class="hc-brand" href="#hc-top" aria-label="zz.naoy 首页"><span class="hc-mark">${symbol}</span><span>zz.naoy<span class="hc-brand-dot">/</span></span></a>`
const nav = () => `<header class="hc-header hc-wrap">${brand}<nav aria-label="主导航"><a href="#hc-capabilities">平台能力</a><a href="#hc-start">快速接入</a><a href="#hc-faq">常见问题</a></nav><a class="hc-nav-cta" href="/dashboard" target="_top">进入控制台 ${arrow}</a></header>`
const actions = (primary = '开始构建', secondary = '了解接入方式') => `<div class="hc-actions"><a class="hc-button hc-primary" href="/dashboard" target="_top">${primary} ${arrow}</a><a class="hc-button hc-secondary" href="#hc-start">${secondary} <span aria-hidden="true">→</span></a></div>`
const providers = () => `<div class="hc-providers" aria-label="模型生态示例"><span class="hc-provider"><b class="hc-provider-icon hc-claude" aria-hidden="true">✳</b> Claude</span><span class="hc-provider"><b class="hc-provider-icon hc-gpt" aria-hidden="true">◎</b> GPT</span><span class="hc-provider"><b class="hc-provider-icon hc-gemini" aria-hidden="true">✦</b> Gemini</span><span class="hc-provider hc-provider-more"><b aria-hidden="true">＋</b> 更多可能</span></div>`
const note = '<p class="hc-model-note">模型生态示意，实际开放模型与价格以控制台为准。</p>'
const steps = `<div class="hc-steps"><article><span class="hc-step-number">01</span><h3>进入控制台</h3><p>登录账户，查看可用模型与账户设置。</p></article><article><span class="hc-step-number">02</span><h3>创建专属密钥</h3><p>在密钥管理中创建 API Key（接口访问凭证）。</p></article><article><span class="hc-step-number">03</span><h3>连接你的应用</h3><p>按照控制台提供的接口地址与模型名称完成配置。</p></article></div>`
const start = () => `<section class="hc-section hc-wrap hc-start" id="hc-start"><div class="hc-section-heading"><div><p class="hc-eyebrow">GET STARTED / 快速接入</p><h2>从想法，到第一次调用。</h2></div><a class="hc-text-link" href="/keys" target="_top">前往密钥管理 ${arrow}</a></div>${steps}</section>`
const faq = `<section class="hc-section hc-wrap hc-faq" id="hc-faq"><div><p class="hc-eyebrow">GOOD QUESTIONS / 常见问题</p><h2>开始之前，<br>你可能想知道。</h2></div><div class="hc-faq-list"><details><summary>可以接入哪些模型？<span aria-hidden="true">＋</span></summary><p>请以登录后控制台展示的模型及所属分组为准。页面中的品牌名称仅用于展示模型生态，不代表所有模型均已开放。</p></details><details><summary>已有应用需要重新开发吗？<span aria-hidden="true">＋</span></summary><p>如果你的应用支持所选模型的兼容接口，通常可以通过调整接口地址、模型名称和访问密钥完成接入。具体参数请按控制台说明配置。</p></details><details><summary>如何查看调用记录与费用？<span aria-hidden="true">＋</span></summary><p>登录后可在控制台查看用量及调用记录。实际计费规则、余额与可用额度以账户页面显示为准。</p></details></div></section>`
const footer = () => `<footer class="hc-footer hc-wrap">${brand}<p>让连接更简单，让创造更自由。</p><a href="/key-usage" target="_top">密钥用量查询 ${arrow}</a></footer>`
const cta = (title = '下一次创造，从这里开始。') => `<section class="hc-final-cta hc-wrap"><div><p class="hc-eyebrow">YOUR NEXT CHAPTER / 开始创造</p><h2>${title}</h2></div><a class="hc-button hc-primary" href="/dashboard" target="_top">进入控制台 ${arrow}</a></section>`
const layout = (theme, content, end) => `<div class="hc-site hc-${theme}" id="hc-top"><a class="hc-skip" href="#hc-main">跳到主要内容</a>${nav()}<main id="hc-main">${content}${start()}${faq}${cta(end)}</main>${footer()}</div>`

const orbitArt = `<div class="hc-orbit-art" role="img" aria-label="多个模型围绕统一接口连接的抽象轨道示意"><div class="hc-orbit-glow"></div><svg class="hc-orbit-lines" viewBox="0 0 600 600" fill="none" aria-hidden="true"><defs><radialGradient id="hc-orbit-sphere" cx="30%" cy="20%" r="90%"><stop stop-color="#464d45"/><stop offset=".45" stop-color="#141b16"/><stop offset="1" stop-color="#060908"/></radialGradient><linearGradient id="hc-orbit-line"><stop stop-color="#d4edab" stop-opacity=".1"/><stop offset=".5" stop-color="#d4edab"/><stop offset="1" stop-color="#d4edab" stop-opacity=".1"/></linearGradient></defs><circle cx="300" cy="300" r="227" stroke="#333e31" stroke-dasharray="2 8"/><circle cx="300" cy="300" r="177" stroke="#4c5d41" stroke-opacity=".5"/><ellipse cx="300" cy="300" rx="268" ry="95" transform="rotate(-35 300 300)" stroke="url(#hc-orbit-line)"/><ellipse cx="300" cy="300" rx="230" ry="120" transform="rotate(45 300 300)" stroke="#536445" stroke-opacity=".55"/><circle cx="300" cy="300" r="119" fill="url(#hc-orbit-sphere)" stroke="#819c69" stroke-opacity=".55"/><ellipse cx="300" cy="300" rx="119" ry="42" transform="rotate(-35 300 300)" stroke="#556448" stroke-opacity=".3"/><path d="M259 338v-76h21l47 76h16v-76" stroke="#d4edab" stroke-width="4"/><circle cx="110" cy="431" r="5" fill="#d4edab"/><circle cx="440" cy="166" r="4" fill="#d4edab"/><circle cx="438" cy="484" r="3" fill="#8b9e7f"/></svg><span class="hc-orbit-tag hc-tag-one">✳ <span>Claude</span></span><span class="hc-orbit-tag hc-tag-two">✦ <span>Gemini</span></span><span class="hc-orbit-tag hc-tag-three">◎ <span>GPT</span></span><div class="hc-art-caption"><span class="hc-led"></span> ONE GATEWAY. MORE POSSIBILITIES.<small>统一接入 · 架构示意</small></div></div>`

const porcelainArt = `<div class="hc-porcelain-art" role="img" aria-label="蓝色几何连接结构与统一接口示意"><div class="hc-art-grid"></div><span class="hc-art-index">FIG. 01 — CONNECTED INTELLIGENCE</span><div class="hc-blue-ribbon hc-ribbon-back"></div><div class="hc-blue-ribbon hc-ribbon-front"></div><div class="hc-porcelain-dot"></div><div class="hc-porcelain-label"><span>复杂的模型世界</span><b>一个简洁的入口 ${arrow}</b></div><div class="hc-porcelain-tag">N / ONE CONNECTION</div></div>`

const prismArt = `<div class="hc-prism-art" role="img" aria-label="光线汇聚到中央棱镜的抽象模型连接示意"><div class="hc-prism-halo"></div><svg viewBox="0 0 1000 420" fill="none" aria-hidden="true"><defs><linearGradient id="hc-prism-face-a" x1="395" y1="60" x2="590" y2="365" gradientUnits="userSpaceOnUse"><stop stop-color="#fae9ff" stop-opacity=".7"/><stop offset=".4" stop-color="#8d61ff" stop-opacity=".3"/><stop offset="1" stop-color="#4c2b91" stop-opacity=".6"/></linearGradient><linearGradient id="hc-prism-face-b"><stop stop-color="#87d9ff" stop-opacity=".45"/><stop offset="1" stop-color="#d091ff" stop-opacity=".15"/></linearGradient></defs><path d="M0 276L500 203L1000 276M86 363L500 203L914 363M165 88L500 203L835 88" stroke="#9b79e2" stroke-opacity=".22"/><ellipse cx="500" cy="260" rx="355" ry="112" stroke="#b699ff" stroke-opacity=".18"/><ellipse cx="500" cy="260" rx="270" ry="72" stroke="#b699ff" stroke-opacity=".2"/><path d="M500 45L640 245L500 365L360 245Z" fill="url(#hc-prism-face-a)" stroke="#e5d5ff" stroke-opacity=".6"/><path d="M500 45V365L640 245Z" fill="url(#hc-prism-face-b)" stroke="#d7c1ff" stroke-opacity=".5"/><path d="M360 245L500 202L640 245M500 45L500 202L500 365" stroke="#eddfff" stroke-opacity=".55"/><circle cx="500" cy="202" r="5" fill="#fff"/><circle cx="145" cy="277" r="3" fill="#bda4ef"/><circle cx="855" cy="277" r="3" fill="#bda4ef"/></svg><span class="hc-prism-tag hc-prism-one">✳ Claude</span><span class="hc-prism-tag hc-prism-two">◎ GPT</span><span class="hc-prism-tag hc-prism-three">✦ Gemini</span><span class="hc-prism-base">想法在此汇聚，可能由此展开。</span></div>`

const terminal = `<div class="hc-terminal"><div class="hc-terminal-top"><span class="hc-terminal-dots" aria-hidden="true">● ● ●</span><span>接入配置示例</span><span>⌘</span></div><div class="hc-terminal-body"><div class="hc-terminal-path">~/your-next-idea <span>main*</span></div><p><span class="hc-code-green">❯</span> 配置你的应用</p><pre><code><span class="hc-code-muted"># 使用控制台提供的实际配置</span>
<span class="hc-code-purple">BASE_URL</span> = <span class="hc-code-green">&quot;你的接口地址&quot;</span>
<span class="hc-code-purple">API_KEY</span>  = <span class="hc-code-green">&quot;你的访问密钥&quot;</span>
<span class="hc-code-purple">MODEL</span>    = <span class="hc-code-green">&quot;可用模型名称&quot;</span></code></pre><div class="hc-terminal-divider"></div><p class="hc-terminal-result"><span>✓</span> 一个入口，连接你的工具</p><p class="hc-terminal-result"><span>✓</span> 密钥与用量，集中管理</p><p class="hc-terminal-prompt"><span class="hc-code-green">❯</span> build something great<span class="hc-cursor" aria-hidden="true"></span></p></div><div class="hc-terminal-bottom"><span><i class="hc-led"></i> 配置演示 · 非实时请求</span><span>UTF-8</span></div></div>`

const originalGoldArt = `<div class="hc-gold-art" role="img" aria-label="金色细线编织的抽象无限连接雕塑"><svg viewBox="0 0 600 590" fill="none" aria-hidden="true"><defs><linearGradient id="hc-gold-stroke" x1="100" y1="80" x2="530" y2="500" gradientUnits="userSpaceOnUse"><stop stop-color="#504331"/><stop offset=".38" stop-color="#ecd5a6"/><stop offset=".7" stop-color="#9c8157"/><stop offset="1" stop-color="#3a3326"/></linearGradient></defs>${Array.from({ length: 24 }, (_, index) => `<ellipse cx="300" cy="292" rx="${100 + index * 3.3}" ry="${226 - index * 2.1}" transform="rotate(${index * 7.5} 300 292)" stroke="url(#hc-gold-stroke)" stroke-opacity="${0.28 + index * 0.023}" stroke-width=".8"/>`).join('')}<circle cx="300" cy="292" r="52" fill="#131410" stroke="#bda477" stroke-opacity=".4"/><path d="M282 309v-34h9l20 34h7v-34" stroke="#d2bc94" stroke-width="2"/></svg><span class="hc-gold-art-label">THE ART OF CONNECTION</span><span class="hc-gold-coordinate">01 — ∞ / AN OPEN WORLD</span></div>`
