import { actions, providers, note, layout, orbitArt, porcelainArt, prismArt, terminal, goldArt } from './concepts.mjs'

export const concepts = [
  {
    id: '01-orbit',
    name: '引力黑曜',
    html: layout('orbit', `<section class="hc-hero hc-wrap hc-split"><div class="hc-hero-copy"><p class="hc-eyebrow"><span class="hc-led"></span> THE INTELLIGENCE LAYER / 智能连接层</p><h1>连接智能。<br>释放<span class="hc-accent">无限可能。</span></h1><p class="hc-lead">不必在不同模型之间反复切换。<br>用一个清晰的入口，连接你的下一次创造。</p>${actions('进入控制台', '探索平台')}<div class="hc-hero-footnote"><span>01 / ONE CONNECTION</span><span>让复杂，归于简单。</span></div></div>${orbitArt}</section><section class="hc-ecosystem hc-wrap"><div class="hc-ecosystem-label"><span class="hc-eyebrow">A CONNECTED ECOSYSTEM</span><span>连接多元模型生态</span></div>${providers()}</section><section class="hc-section hc-wrap" id="hc-capabilities"><div class="hc-section-heading"><div><p class="hc-eyebrow">BUILT FOR YOUR NEXT / 为创造而生</p><h2>强大的背后，是简单。</h2></div><p>少一些连接的阻力，<br>多一些专注的空间。</p></div><div class="hc-orbit-cards"><article class="hc-feature-card"><span class="hc-feature-number">01 / CONNECT</span><div class="hc-mini-network" aria-hidden="true"><span>✳</span><i></i><b>N</b><i></i><span>✦</span></div><h3>一个入口，多种可能</h3><p>以统一入口管理模型调用，让工具与工作流更容易连接。</p></article><article class="hc-feature-card"><span class="hc-feature-number">02 / CONTROL</span><div class="hc-mini-key" aria-hidden="true"><span>⌁</span><b>sk · •••• •••• ••••</b></div><h3>访问权限，尽在掌握</h3><p>集中管理访问密钥，让不同应用的使用边界更加清晰。</p></article><article class="hc-feature-card"><span class="hc-feature-number">03 / UNDERSTAND</span><div class="hc-mini-bars" aria-hidden="true">${[25,40,32,55,45,70,60,90,76,100,88,110].map(height => `<i style="height:${height / 2}px"></i>`).join('')}</div><h3>每一次使用，都有迹可循</h3><p>查看调用与用量记录，把关注点放回真正重要的创造。</p></article></div>${note}</section>`),
  },
  {
    id: '02-porcelain',
    name: '极简白瓷',
    light: true,
    html: layout('porcelain', `<section class="hc-hero hc-wrap hc-split"><div class="hc-hero-copy"><p class="hc-eyebrow"><span class="hc-blue-dot"></span> LESS FRICTION. MORE CREATION.</p><h1>一个入口。<br><span class="hc-accent">万千可能。</span></h1><p class="hc-lead">好的工具，让复杂隐于幕后。<br>连接你需要的 AI，把时间留给更好的想法。</p>${actions('开启你的创造', '看看如何接入')}<div class="hc-porcelain-hero-note"><span class="hc-small-rule"></span> 为开发者而构建，也为每一个好奇的你。</div></div>${porcelainArt}</section><section class="hc-porcelain-ecosystem hc-wrap"><p class="hc-eyebrow">DIFFERENT MODELS. ONE FAMILIAR PLACE.</p>${providers()}${note}</section><section class="hc-section hc-wrap" id="hc-capabilities"><div class="hc-section-heading"><div><p class="hc-eyebrow">SIMPLY POWERFUL / 简单，但不简单</p><h2>恰到好处的能力。<br><span class="hc-muted">不多一分复杂。</span></h2></div><p>连接、管理、查看。<br>让每一步都清晰自然。</p></div><div class="hc-porcelain-features"><article><span class="hc-outline-icon" aria-hidden="true">↗</span><span class="hc-feature-number">01</span><h3>更少配置，更快开始</h3><p>按兼容接口接入你的应用，不再让重复配置打断灵感。</p></article><article><span class="hc-outline-icon" aria-hidden="true">⌘</span><span class="hc-feature-number">02</span><h3>不同模型，统一管理</h3><p>在同一个控制台管理密钥与模型使用，让工作保持有序。</p></article><article><span class="hc-outline-icon" aria-hidden="true">◴</span><span class="hc-feature-number">03</span><h3>清楚使用，心中有数</h3><p>用量记录与调用明细集中呈现，让每次使用更加明了。</p></article></div></section>`, '让好想法，自然发生。'),
  },
  {
    id: '03-prism',
    name: '极光棱镜',
    html: layout('prism', `<section class="hc-hero hc-wrap hc-center"><p class="hc-prism-badge"><span aria-hidden="true">✦</span> 让每一种智能，为你的灵感所用</p><h1>想象，不设边界。<br><span class="hc-accent">连接，就从这里。</span></h1><p class="hc-lead">汇聚多元模型能力，连接你的应用与创意。<br>从第一行代码，到下一个令人惊叹的作品。</p>${actions('探索你的可能', '了解平台能力')}${prismArt}</section><section class="hc-section hc-wrap hc-prism-capabilities" id="hc-capabilities"><div class="hc-section-heading"><div><p class="hc-eyebrow">WHERE IDEAS TAKE SHAPE / 让想法成形</p><h2>你的灵感，值得更大的舞台。</h2></div></div><div class="hc-prism-bento"><article class="hc-prism-wide"><div><span class="hc-feature-number">01 / ALL TOGETHER</span><h3>多种智能，一处汇聚。</h3><p>写作、编程、推理与探索。<br>按你的任务选择适合的模型。</p></div><div class="hc-prism-model-stack">${providers()}</div></article><article><span class="hc-prism-card-icon" aria-hidden="true">⌘</span><span class="hc-feature-number">02 / YOUR WORKFLOW</span><h3>融入你的工作方式。</h3><p>通过兼容接口，将模型能力接入你熟悉的应用。</p></article><article><span class="hc-prism-card-icon" aria-hidden="true">◈</span><span class="hc-feature-number">03 / IN YOUR HANDS</span><h3>创造，也保持掌控。</h3><p>密钥、调用与用量信息，在控制台集中管理。</p></article></div>${note}</section>`, '把下一次灵感，变成现实。'),
  },
  {
    id: '04-terminal',
    name: '终端绿洲',
    html: layout('terminal', `<div class="hc-terminal-banner"><span class="hc-wrap"><span>BUILD WITHOUT THE BUSYWORK</span><span>面向开发者的模型接入入口 ↗</span></span></div><section class="hc-hero hc-wrap hc-split"><div class="hc-hero-copy"><p class="hc-eyebrow"><span class="hc-led"></span> FOR BUILDERS, BY DESIGN.</p><h1>少一点配置。<br><span class="hc-accent">多一点创造<span class="hc-code-underscore">_</span></span></h1><p class="hc-lead">模型连接不该成为项目里最复杂的部分。<br>统一接入、管理密钥、查看用量。然后，继续构建。</p>${actions('打开控制台', '阅读接入步骤')}<div class="hc-dev-tags"><span>兼容接口</span><span>密钥管理</span><span>用量追踪</span></div></div>${terminal}</section><section class="hc-terminal-ecosystem hc-wrap"><span class="hc-eyebrow">// 模型生态示例</span>${providers()}${note}</section><section class="hc-section hc-wrap" id="hc-capabilities"><div class="hc-section-heading"><div><p class="hc-eyebrow">[ THE TOOLKIT ]</p><h2>把基础工作，交给基础设施。</h2></div><span class="hc-dev-comment">// focus_on_what_matters</span></div><div class="hc-dev-features"><article><span class="hc-dev-feature-icon" aria-hidden="true">&gt;_</span><div><span class="hc-feature-number">01 / INTEGRATE</span><h3>接入，不绕弯路。</h3><p>使用控制台提供的接口地址与密钥，连接支持兼容协议的工具。</p></div></article><article><span class="hc-dev-feature-icon" aria-hidden="true">{ }</span><div><span class="hc-feature-number">02 / ORGANIZE</span><h3>每个项目，各就各位。</h3><p>集中管理应用使用的访问密钥，让不同项目的配置更清楚。</p></div></article><article><span class="hc-dev-feature-icon" aria-hidden="true">▥</span><div><span class="hc-feature-number">03 / OBSERVE</span><h3>不靠猜，看记录。</h3><p>从控制台查看调用记录与用量，了解应用实际的使用情况。</p></div></article></div></section>`, '你的下一个项目，准备好了吗？'),
  },
  {
    id: '05-atelier',
    name: '鎏金典藏',
    html: layout('atelier', `<section class="hc-hero hc-wrap hc-split"><div class="hc-hero-copy"><p class="hc-eyebrow">A MORE CONSIDERED CONNECTION</p><p class="hc-atelier-display" lang="en">Intelligence,<br><em>beautifully</em><br>connected.</p><h1>连接智能，自有章法。</h1><p class="hc-lead">让技术退居幕后，让创造走向台前。<br>一个从容、清晰的入口，通向更广阔的智能世界。</p>${actions('开启探索', '认识平台')}</div>${goldArt}<span class="hc-atelier-edition">EST. FOR THE NEXT IDEA · 01 — ∞</span></section><section class="hc-atelier-ecosystem hc-wrap"><span class="hc-eyebrow">A WORLD OF INTELLIGENCE</span>${providers()}${note}</section><section class="hc-section hc-wrap" id="hc-capabilities"><div class="hc-section-heading"><div><p class="hc-eyebrow">THE ESSENTIALS / 回归本质</p><h2>简于形，<span class="hc-accent">精于心。</span></h2></div><p>真正好的体验，不需要喧哗。<br>只需让每一次使用，恰如其分。</p></div><div class="hc-atelier-features"><article><span class="hc-roman">I.</span><div><h3>汇聚，而不繁复。</h3><p>多元模型，一个入口。<br>在更大的选择空间里，保持清晰。</p></div><span class="hc-atelier-word">Connection</span></article><article><span class="hc-roman">II.</span><div><h3>掌握，而不费力。</h3><p>访问密钥，集中管理。<br>让每个应用，拥有自己的连接方式。</p></div><span class="hc-atelier-word">Control</span></article><article><span class="hc-roman">III.</span><div><h3>明晰，而不打扰。</h3><p>调用用量，有迹可循。<br>用清楚的信息，支持从容的决定。</p></div><span class="hc-atelier-word">Clarity</span></article></div></section>`, '让卓越的想法，拥有好的开始。'),
  },
]
